// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from "@hotwired/stimulus"
import HelloController from "./hello_controller"
import CameraController from "./camera_controller"
import PhotoSwitcherController from "./photo_switcher_controller"
import DropdownController from "./dropdown_controller"
import LoadingController from "./loading_controller"

window.Stimulus = Application.start()
Stimulus.register("hello", HelloController)
Stimulus.register("camera", CameraController)
Stimulus.register("photo-switcher", PhotoSwitcherController)
Stimulus.register("dropdown", DropdownController)
Stimulus.register("loading", LoadingController)
